x-environment:
  &COMMON_ENV_VARS
  # DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DJANGO_DEBUG: ${DJANGO_DEBUG}
  # DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET_PRODUCTION: ${PLAID_SECRET_PRODUCTION}
  PLAID_SECRET_SANDBOX: ${PLAID_SECRET_SANDBOX}
  PLAID_ENV: ${PLAID_ENV}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  REACT_APP_API_HOST: http://backend:8000
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      <<: *COMMON_ENV_VARS
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_HOST: http://backend:8000
    depends_on:
      - backend

  # mobile:
  #   build:
  #     context: ./frontend/mobile
  #     dockerfile: Dockerfile
  #   networks:
  #     - app_network
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     EXPO_API_HOST: http://backend:8000
  #   volumes:
  #     - ./mobile-frontend:/app
  #   tty: true
  #   depends_on:
  #     - backend
    
  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
volumes:
  postgres_data:
      


