x-environment:
  &COMMON_ENV_VARS
  # DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DJANGO_DEBUG: ${DJANGO_DEBUG}
  # DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
  PLAID_CLIENT_ID: ${PLAID_CLIENT_ID}
  PLAID_SECRET_PRODUCTION: ${PLAID_SECRET_PRODUCTION}
  PLAID_SECRET_SANDBOX: ${PLAID_SECRET_SANDBOX}
  PLAID_ENV: ${PLAID_ENV}
  PLAID_PRODUCTS: ${PLAID_PRODUCTS}
  PLAID_COUNTRY_CODES: ${PLAID_COUNTRY_CODES}
  PLAID_REDIRECT_URI: ${PLAID_REDIRECT_URI}
  REACT_APP_API_HOST: http://backend:8000

networks:
  app_network:
    name: app_network

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "8000:8000"
    environment:
      <<: *COMMON_ENV_VARS

  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_HOST: http://backend:8000
    depends_on:
      - backend

  mobile:
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "3000:3000"
    environment:
      EXPO_API_HOST: http://backend:8000
    volumes:
      - ./mobile-frontend:/app
    tty: true
    depends_on:
      - backend

