# Generated by Django 5.1.4 on 2026-10-09 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='account',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='networthhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='access_token',
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_item',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.plaiditem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('step', models.CharField(choices=[('fetch_transactions', 'Fetch Transactions'), ('update_db', 'Update Database')], default=None, max_length=50, null=True)),
                ('added_count', models.IntegerField(default=0)),
                ('modified_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('plaid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plaiditem')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountBalanceHistory',
        ),
        migrations.DeleteModel(
            name='Cursor',
        ),
        migrations.DeleteModel(
            name='Liability',
        ),
        migrations.DeleteModel(
            name='NetWorthHistory',
        ),
    ]
